env:
  browser: true
  es6: true
  commonjs: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  {
    "indent": ["error", 2, { "SwitchCase": 1, "flatTernaryExpressions": true }],
    "semi": ["error", "never"],
    "quotes": ["error", "single"],
    "linebreak-style": ["error", "unix"],
    "no-console": ["error", { "allow": ["log", "warn", "error"] }],
    "react/jsx-indent": ["warn", 2],
    "react/jsx-indent-props": ["warn", 2],
    "react/jsx-uses-vars": "error",
    "react/jsx-uses-react": "error",
    "react/prop-types": ["warn", { ignore: ["children"] }],
    "react/display-name": ["off", { "ignoreTranspilerName": false }],
    "react/require-default-props":
      ["error", { forbidDefaultForRequired: true }],
    "react/jsx-props-no-multi-spaces": ["warn"],
    "react/jsx-handler-names": "error",
    "no-unused-vars":
      ["warn", { "vars": "all", "args": "none", "caughtErrors": "none" }],
  }
