version: '2.1'

services:
  web:
    image: welkin-portal-eslint
    environment: 
      - DEBUG
    build: .
    ports:
      - 80:80
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - webnet
networks:
  webnet: